[build]
  base = "q2/library-management-system-main"
  command = "bash netlify_build.sh"
  publish = "q2/library-management-system-main/build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
